spring:
    datasource:
        url: 
        username: 
        password: 
    output:
        ansi:
            enabled: ALWAYS 

server:
    port: 8282                             

logging:
    level:
        com:
            skillstorm: debug